// <auto-generated />
namespace Contactini.DAL.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProfilePicturUpdate1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProfilePicturUpdate1));
        
        string IMigrationMetadata.Id
        {
            get { return "201808290957098_ProfilePicturUpdate1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
