// <auto-generated />
namespace Contactini.DAL.AppMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatemessagemodel_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemessagemodel_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201809121736283_update message model_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
