// <auto-generated />
namespace Contactini.DAL.AppMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class chnagingphotolisttophotoinmissionmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chnagingphotolisttophotoinmissionmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201809040100359_chnaging photolist to photo in mission model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
