// <auto-generated />
namespace Contactini.DAL.AppMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changestarstypetofloat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestarstypetofloat));
        
        string IMigrationMetadata.Id
        {
            get { return "201809261610417_change stars type to float"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
